### ISSUE TITLE
rem的计算

### ISSUE THREAD

**Issue by GrowingFun** [bailicangdu/vue2-happyfri#73]
```css
    .top_tips{
        position: absolute;
        height: 7.35rem;
        width: 3.25rem;
        top: -1.3rem;
        right: 1.6rem;
        background: url(../images/WechatIMG2.png) no-repeat;
        background-size: 100% 100%;
        z-index: 10;
    }
    ```
1. 请问如上rem的值是手工计算的还是用什么工具，怎么维护？
2. <style lang="less" > 使用嵌套时，在webstrom中会有错误语法提示：}  expected，
改为
<style lang="less" rel="stylesheet/less">后错误提示消失，不知道你那边有没有同样的问题？
